//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecosave
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing_Table
    {
        public string ID { get; set; }
        public string Fuel_Charge { get; set; }
        public string Energy_Charge { get; set; }
        public string Exchange_Rate { get; set; }
        public string Reading_Type { get; set; }
        public string Customer_Charge { get; set; }
        public string IPP_Charge { get; set; }
        public string Demand_Charge { get; set; }
    }
}
