//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecosave
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing_Table
    {
        public int ID { get; set; }
        public Nullable<double> Energy_Used { get; set; }
        public Nullable<double> Fuel_Charge { get; set; }
        public Nullable<double> Energy_Charge { get; set; }
        public Nullable<double> Exchange_Rate { get; set; }
        public string Reading_Type { get; set; }
        public Nullable<double> Customer_Charge { get; set; }
        public Nullable<double> IPP_Charge { get; set; }
        public Nullable<double> Demand_Charge { get; set; }
        public Nullable<double> Final_Charge { get; set; }
    }
}
