//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecosave
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculator
    {
        public string ID { get; set; }
        public Nullable<int> Power_Average_1 { get; set; }
        public Nullable<int> Power_Average_2 { get; set; }
        public Nullable<int> Power_Average_3 { get; set; }
        public Nullable<int> Power_Average_4 { get; set; }
        public Nullable<int> Power_Average_5 { get; set; }
        public Nullable<int> Power_Average_6 { get; set; }
        public Nullable<int> Power_Average_7 { get; set; }
        public Nullable<int> Power_Average_8 { get; set; }
        public Nullable<int> Power_Average_9 { get; set; }
        public Nullable<int> Power_Average_10 { get; set; }
    }
}
