//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecosave
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECOSAVEEntities : DbContext
    {
        public ECOSAVEEntities()
            : base("name=ECOSAVEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Billing_Table> Billing_Tables { get; set; }
        public virtual DbSet<Calculator> Calculators { get; set; }
        public virtual DbSet<Devices_Table> Devices_Tables { get; set; }
        public virtual DbSet<Houses_Table> Houses_Tables { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Person_Table> Person_Tables { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
