//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecosave
{
    using System;
    using System.Collections.Generic;
    
    public partial class Houses_Table
    {
        public int ID { get; set; }
        public int Number_of_Rooms { get; set; }
        public int Number_of_Devices_per_Room { get; set; }
    }
}
